RestaurantManagement/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('registerApp.urls')),
    path('restaurant/', include('restaurantApp.urls')),
]

registerApp/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('sign-up/', sign_up_view, name='sign_up'),
    path('', login_view.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
]

restaurantApp/urls.py
from django.urls import path
from .views import *

app_name = 'restaurantApp'

urlpatterns = [
    path('home/', index_view, name='home'),
    path('add-restaurant/', add_restaurant_view, name='add_restaurant'),
    path('edit-restaurant/<int:restaurant_id>/', edit_restaurant_view, name='edit_restaurant'),
    path('add-menu/<int:restaurant_id>/', add_menu_view, name='add_menu'),
    path('edit-menu/<int:menu_id>/', edit_menu_view, name='edit_menu'),
    path('add-menu-items/<int:menu_id>/', add_menu_item_view, name='add_menu_item'),
    path('edit-menu-items/<int:menu_item_id>/', edit_menu_item_view, name='edit_menu_item'),
    path('menu-items/<int:menu_id>/', menu_view, name='menu_view'),
    path('checkout/', checkout_view, name='checkout'),
    path('success/', payment_success, name='payment_success'),
    path('order/<str:item_id>/', order_view, name='order'),
    path('payment-process/<str:order_id>/', process_payment, name='process_payment'),

]

templates/index/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
</head>
<body>
{% if request.user.profile.role == 'owner' %}
    <a href="{% url 'restaurantApp:add_restaurant' %}">Add Restaurant</a>
    <br>


{% else %}
    <h2>All Restaurant List</h2>
    <p><a href="{% url 'logout' %}">logout</a></p>
    <hr>
    {% for all_restaurant_list in all_restaurant_lists %}
        <p> Restaurant Name: {{ all_restaurant_list }}</p>
        <p>Menu list</p>
        {% for menu in all_restaurant_list.menus.all %}
            <ul>
                <li>{{ menu.menu_name }}-- <a href="{% url 'restaurantApp:menu_view' menu.id %}">view menu</a></li>
            </ul>
        {% endfor %}
        <hr>

    {% endfor %}
{% endif %}
</body>
</html>