RestaurantManagement/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('registerApp.urls')),
    path('restaurant/', include('restaurantApp.urls')),
]

registerApp/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('sign-up/', sign_up_view, name='sign_up'),
    path('', login_view.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
]

restaurantApp/urls.py
from django.urls import path
from .views import *

app_name = 'restaurantApp'

urlpatterns = [
    path('home/', index_view, name='home'),
    path('add-restaurant/', add_restaurant_view, name='add_restaurant'),
    path('edit-restaurant/<int:restaurant_id>/', edit_restaurant_view, name='edit_restaurant'),
    path('add-menu/<int:restaurant_id>/', add_menu_view, name='add_menu'),
    path('edit-menu/<int:menu_id>/', edit_menu_view, name='edit_menu'),
    path('add-menu-items/<int:menu_id>/', add_menu_item_view, name='add_menu_item'),
    path('edit-menu-items/<int:menu_item_id>/', edit_menu_item_view, name='edit_menu_item'),
    path('menu-items/<int:menu_id>/', menu_view, name='menu_view'),
    path('checkout/', checkout_view, name='checkout'),
    path('success/', payment_success, name='payment_success'),
    path('order/<str:item_id>/', order_view, name='order'),
    path('payment-process/<str:order_id>/', process_payment, name='process_payment'),

]

templates/restaurant/add-menu-item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add menu items</title>
</head>
<body>
<form method="POST">
    {{ form.as_p }}
    {% csrf_token %}
    <button>Add items</button>
    <a href="{% url 'restaurantApp:add_restaurant' %}">Restaurant List</a>
</form>
<p>Menu Name: {{ menu_obj.menu_name }} </p>
<p>Menu Items List</p>
{% for all_menu_item in all_menu_items %}
<ul>
    <li>Item Name :{{ all_menu_item.menu_items_name }}-- <a href="{% url 'restaurantApp:edit_menu_item' all_menu_item.id %}">Edit</a></li>
    <li>Item Description :{{ all_menu_item.menu_items_desc }}</li>
    <li>Item Price :{{ all_menu_item.menu_items_price }}</li>
</ul>
{% endfor %}


</body>
</html>

templates/restaurant/add-menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add menu</title>
</head>
<body>
<form method="POST">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit">Add Menu</button>
    <a href="{% url 'restaurantApp:add_restaurant' %}">Restaurant List</a>
</form>
<p>Restaurant Name : {{ restaurant_obj.restaurant_name }}</p>
<p>Menu list and menu items: </p>
{% for all_menu_list in all_menu_lists %}
    <li>{{ all_menu_list }} -- <a href="{% url 'restaurantApp:edit_menu' all_menu_list.id %}"> Edit menu</a>--<a href="{% url 'restaurantApp:add_menu_item' all_menu_list.id %}"> Add items</a></li>
    {% for i in all_menu_list.menuItems.all %}
{#        {{ i. }}#}
        {% endfor %}
    <br>

{% endfor %}

</body>
</html>

templates/restaurant/edit-menu-item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit menu items</title>
</head>
<body>
<form method="POST">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit">Edit items</button>
</form>
</body>
</html>

templates/restaurant/edit-menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit menu</title>
</head>
<body>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Edit Menu</button>

</form>
</body>
</html>

templates/restaurant/edit-restaurant-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Restaurant</title>
</head>
<body>
<form method="POST">
    <p>Eid Restaurant Name:</p>
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit">Edit</button>
</form>
</body>
</html>

templates/restaurant/restaurant-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Restaruant List</title>
</head>
<body>
<form method="POST">
    <p> Add Restaurant</p>
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit">Add</button>
</form>
<p>Your Restaurant Lists:</p>
{% for restaurant_list in restaurant_lists %}
    <li>{{ restaurant_list }}
        <a href="{% url 'restaurantApp:edit_restaurant' restaurant_list.id %}">Edit</a>
        <a href="{% url 'restaurantApp:add_menu' restaurant_list.id %}">Add Menu</a>

    </li>
{% endfor %}
</body>
</html>

templates/restaurant/view-menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>View menu</title>
</head>
<body>
<p>Menu Name : {{ menu_obj.menu_name }}</p>
{% for menu_list in menu_lists %}
    <p>Item Name: {{ menu_list.menu_items_name }}</p>
    <p>Item Description: {{ menu_list.menu_items_desc }}</p>
    <p>Item Price: {{ menu_list.menu_items_price }}</p>
    <a href="{% url 'restaurantApp:order' menu_list.id %}">Order Now</a>
{% endfor %}

</body>
</html>