RestaurantManagement/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('registerApp.urls')),
    path('restaurant/', include('restaurantApp.urls')),
]

registerApp/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('sign-up/', sign_up_view, name='sign_up'),
    path('', login_view.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
]

restaurantApp/urls.py
from django.urls import path
from .views import *

app_name = 'restaurantApp'

urlpatterns = [
    path('home/', index_view, name='home'),
    path('add-restaurant/', add_restaurant_view, name='add_restaurant'),
    path('edit-restaurant/<int:restaurant_id>/', edit_restaurant_view, name='edit_restaurant'),
    path('add-menu/<int:restaurant_id>/', add_menu_view, name='add_menu'),
    path('edit-menu/<int:menu_id>/', edit_menu_view, name='edit_menu'),
    path('add-menu-items/<int:menu_id>/', add_menu_item_view, name='add_menu_item'),
    path('edit-menu-items/<int:menu_item_id>/', edit_menu_item_view, name='edit_menu_item'),
    path('menu-items/<int:menu_id>/', menu_view, name='menu_view'),
    path('checkout/', checkout_view, name='checkout'),
    path('success/', payment_success, name='payment_success'),
    path('order/<str:item_id>/', order_view, name='order'),
    path('payment-process/<str:order_id>/', process_payment, name='process_payment'),

]

templates/checkout/checkout.html
<!DOCTYPE html>
<html>
<head>
    <title>Payment</title>
    <script src="https://js.stripe.com/v3/"></script>
</head>
<body>
    <h2>Pay for Your Order</h2>

    <!-- Payment form -->
    <form id="payment-form" method="post" action="{% url 'restaurantApp:process_payment' order.id %}">
        {% csrf_token %}

        <div id="card-element"></div>
        <div id="card-errors" role="alert"></div>

        <button type="submit" id="submit-button">Pay Now</button>
    </form>

    <script>
        // Initialize Stripe with your publishable key
        var stripe = Stripe('pk_test_51PrwGXI3rn6BpbALKwh82i3pufZLtvYupcy4ZVkZq9KFl0T1qzd03hE5zuXASeBu8m8apoLSR1vvam7wyHD7hoQ5006zqJjiTJ');
        var elements = stripe.elements();

        var card = elements.create('card');

        // Add an instance of the card Element into the `card-element` <div>
        card.mount('#card-element');

        // Handle real-time validation errors from the card Element
        card.on('change', function(event) {
            var displayError = document.getElementById('card-errors');
            if (event.error) {
                displayError.textContent = event.error.message;
            } else {
                displayError.textContent = '';
            }
        });

        // Handle form submission
        var form = document.getElementById('payment-form');
        form.addEventListener('submit', function(event) {
            event.preventDefault();

            stripe.createToken(card).then(function(result) {
                if (result.error) {
                    // Inform the user if there was an error
                    var errorElement = document.getElementById('card-errors');
                    errorElement.textContent = result.error.message;
                } else {
                    // Send the token to your server
                    stripeTokenHandler(result.token);
                }
            });
        });

        // Submit the form with the token ID
        function stripeTokenHandler(token) {
            var form = document.getElementById('payment-form');
            var hiddenInput = document.createElement('input');
            hiddenInput.setAttribute('type', 'hidden');
            hiddenInput.setAttribute('name', 'stripeToken');
            hiddenInput.setAttribute('value', token.id);
            form.appendChild(hiddenInput);

            // Submit the form
            form.submit();
        }
    </script>
</body>
</html>

templates/checkout/payment_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Payment Success</title>
</head>
<body>
 <h2>Payment Successful!</h2>
    <p>Your payment has been processed successfully. Thank you for your order!</p>
    <a href="{% url 'restaurantApp:home' %}">Back to Restaurant List</a>
</body>
</html>